name: easy_mail
description: "Pure Dart mail protocol parsing & communication library for Flutter and Dart VM."
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0
